### ISSUE TITLE
Crashing on loading a save with only UE4SS

### ISSUE THREAD

**Issue by ValhallaCommunityOfficial** [Nexus-Mods/game-palworld#2]
LoginId:ac91ccbe47c0ccf5f8875d9458182d67
EpicAccountId:

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000024d93195058

XINPUT1_3
XINPUT1_3
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
kernel32
ntdll

**Comment by IDCs** [comment]
Hi there @ValhallaCommunityOfficial,

Thanks for your report - I think I saw your post on the nexus page too.

Lets test something - purge your mods, and browse to the UE4SS mod entry inside your staging folder -> Rename xinput1_3 to xinput1_4 and let us know if that worked.

**Comment by IDCs** [comment]
Also, can you provide screenshots of the game's folder structure?

It looks like every game store distributes the game with a different structure and we may have to make some modifications to support the Epic version too.

**Comment by ExE-Boss** [comment]
You need to use the latest dwmapi‑based experimental build (see UE4SS-RE/RE-UE4SS#309 for details)
