### ISSUE TITLE
Multi mod type support? 

### ISSUE THREAD

**Issue by Dekita** [Nexus-Mods/game-palworld#7]
hi. how should a zip file be structured for uploading on nexus if it contains both a lua mod, and a blueprint logic mod? there doesnt seem to be any support for this and files keep getting placed in the incorrect folder (logic mods) - regardless of the strcuture i use. 

ive tried recreating from 
Palworld
Palworld/Pal
Palworld/Pal/Content

ive tried having two individual folders, one LogicMods, one with a Scripts and enabled.txt etc for the lua side.. 

Am i going to have to upload my one mod as two mods? :'(

**Comment by IDCs** [comment]
Hey there @Dekita - I actually added root modType support this morning in a PR; as long as you keep your mod's structure relative to the game's root path (i.e. `Pal/Binaries`, `Pal/Content`, etc) - it should work just fine. Actually tested with your mod and it worked pretty nicely.

Will close this once https://github.com/Nexus-Mods/game-palworld/pull/8 is merged in.

**Comment by Dekita** [comment]
which mod did you test with? 

I re-enabled vortex install just now to test with the existing mod config menu upload and it again just smooshed everything into logicmods folder. 

the structure for that upload is as you say for it to be;
![image](https://github.com/Nexus-Mods/game-palworld/assets/8195694/50953e3c-d6a0-4bab-aa79-b8f2047db4b3)

**Comment by IDCs** [comment]
That's the one, however the extension update only went out this morning which is why you were still having issues. Sorry about that! Please let me know how it runs with version 0.1.5 of our extension - you shouldn't have to update the mod on the website. Simply update your archive and drag and drop it into the mods page's drop area.

**Comment by Dekita** [comment]
I just tested this and YES! it does indeed work! 
Many apologies. I should have been more patient wit the update rolling out. Very happy to have proper support for this now though <3

**Comment by IDCs** [comment]
Sweet, thanks for confirming :)
